export const APP_NAME = "AI Cold Caller";
export const API_VERSION = "v1";

export const AUTH_ERROR_CODES = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const TENANT_ERROR_CODES = {
  TENANT_CONTEXT_MISSING: "TENANT_CONTEXT_MISSING",
  TENANT_ACCESS_DENIED: "TENANT_ACCESS_DENIED",
  TENANT_INVALID_ORG_ID: "TENANT_INVALID_ORG_ID",
} as const;

export type TenantErrorCode =
  (typeof TENANT_ERROR_CODES)[keyof typeof TENANT_ERROR_CODES];

export const BRANDING_ERROR_CODES = {
  BRANDING_NOT_FOUND: "BRANDING_NOT_FOUND",
  BRANDING_INVALID_LOGO: "BRANDING_INVALID_LOGO",
  BRANDING_DOMAIN_VERIFICATION_FAILED: "BRANDING_DOMAIN_VERIFICATION_FAILED",
  BRANDING_INVALID_COLOR: "BRANDING_INVALID_COLOR",
} as const;

export type BrandingErrorCode =
  (typeof BRANDING_ERROR_CODES)[keyof typeof BRANDING_ERROR_CODES];

export const ONBOARDING_ERROR_CODES = {
  ONBOARDING_ALREADY_COMPLETE: "ONBOARDING_ALREADY_COMPLETE",
  ONBOARDING_VALIDATION_ERROR: "ONBOARDING_VALIDATION_ERROR",
  ONBOARDING_CREATE_ERROR: "ONBOARDING_CREATE_ERROR",
} as const;

export type OnboardingErrorCode =
  (typeof ONBOARDING_ERROR_CODES)[keyof typeof ONBOARDING_ERROR_CODES];

export const USAGE_ERROR_CODES = {
  USAGE_LIMIT_EXCEEDED: "USAGE_LIMIT_EXCEEDED",
  USAGE_CAP_NOT_CONFIGURED: "USAGE_CAP_NOT_CONFIGURED",
  USAGE_INVALID_RESOURCE: "USAGE_INVALID_RESOURCE",
  USAGE_INTERNAL_ERROR: "USAGE_INTERNAL_ERROR",
} as const;

export type UsageErrorCode =
  (typeof USAGE_ERROR_CODES)[keyof typeof USAGE_ERROR_CODES];

export const VAPI_ERROR_CODES = {
  VAPI_SIGNATURE_MISSING: "VAPI_SIGNATURE_MISSING",
  VAPI_SIGNATURE_INVALID: "VAPI_SIGNATURE_INVALID",
  VAPI_NOT_CONFIGURED: "VAPI_NOT_CONFIGURED",
  VAPI_CALL_TRIGGER_FAILED: "VAPI_CALL_TRIGGER_FAILED",
  VAPI_CALL_NOT_FOUND: "VAPI_CALL_NOT_FOUND",
  VAPI_WEBHOOK_PROCESSING_ERROR: "VAPI_WEBHOOK_PROCESSING_ERROR",
} as const;

export type VapiErrorCode =
  (typeof VAPI_ERROR_CODES)[keyof typeof VAPI_ERROR_CODES];
