export const APP_NAME = "AI Cold Caller";
export const API_VERSION = "v1";

export const AUTH_ERROR_CODES = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const TENANT_ERROR_CODES = {
  TENANT_CONTEXT_MISSING: "TENANT_CONTEXT_MISSING",
  TENANT_ACCESS_DENIED: "TENANT_ACCESS_DENIED",
  TENANT_INVALID_ORG_ID: "TENANT_INVALID_ORG_ID",
} as const;

export type TenantErrorCode =
  (typeof TENANT_ERROR_CODES)[keyof typeof TENANT_ERROR_CODES];

export const BRANDING_ERROR_CODES = {
  BRANDING_NOT_FOUND: "BRANDING_NOT_FOUND",
  BRANDING_INVALID_LOGO: "BRANDING_INVALID_LOGO",
  BRANDING_DOMAIN_VERIFICATION_FAILED: "BRANDING_DOMAIN_VERIFICATION_FAILED",
  BRANDING_INVALID_COLOR: "BRANDING_INVALID_COLOR",
} as const;

export type BrandingErrorCode =
  (typeof BRANDING_ERROR_CODES)[keyof typeof BRANDING_ERROR_CODES];

export const ONBOARDING_ERROR_CODES = {
  ONBOARDING_ALREADY_COMPLETE: "ONBOARDING_ALREADY_COMPLETE",
  ONBOARDING_VALIDATION_ERROR: "ONBOARDING_VALIDATION_ERROR",
  ONBOARDING_CREATE_ERROR: "ONBOARDING_CREATE_ERROR",
} as const;

export type OnboardingErrorCode =
  (typeof ONBOARDING_ERROR_CODES)[keyof typeof ONBOARDING_ERROR_CODES];

export const USAGE_ERROR_CODES = {
  USAGE_LIMIT_EXCEEDED: "USAGE_LIMIT_EXCEEDED",
  USAGE_CAP_NOT_CONFIGURED: "USAGE_CAP_NOT_CONFIGURED",
  USAGE_INVALID_RESOURCE: "USAGE_INVALID_RESOURCE",
  USAGE_INTERNAL_ERROR: "USAGE_INTERNAL_ERROR",
} as const;

export type UsageErrorCode =
  (typeof USAGE_ERROR_CODES)[keyof typeof USAGE_ERROR_CODES];

export const VAPI_ERROR_CODES = {
  VAPI_SIGNATURE_MISSING: "VAPI_SIGNATURE_MISSING",
  VAPI_SIGNATURE_INVALID: "VAPI_SIGNATURE_INVALID",
  VAPI_NOT_CONFIGURED: "VAPI_NOT_CONFIGURED",
  VAPI_CALL_TRIGGER_FAILED: "VAPI_CALL_TRIGGER_FAILED",
  VAPI_CALL_NOT_FOUND: "VAPI_CALL_NOT_FOUND",
  VAPI_WEBHOOK_PROCESSING_ERROR: "VAPI_WEBHOOK_PROCESSING_ERROR",
} as const;

export type VapiErrorCode =
  (typeof VAPI_ERROR_CODES)[keyof typeof VAPI_ERROR_CODES];

export const TRANSCRIPTION_ERROR_CODES = {
  TRANSCRIPT_EVENT_PROCESSED: "TRANSCRIPT_EVENT_PROCESSED",
  TRANSCRIPT_PROCESSING_ERROR: "TRANSCRIPT_PROCESSING_ERROR",
  SPEECH_EVENT_PROCESSED: "SPEECH_EVENT_PROCESSED",
  INTERRUPTION_DETECTED: "INTERRUPTION_DETECTED",
  TRANSCRIPT_AGGREGATION_ERROR: "TRANSCRIPT_AGGREGATION_ERROR",
  WS_AUTH_FAILED: "WS_AUTH_FAILED",
  WS_BROADCAST_ERROR: "WS_BROADCAST_ERROR",
} as const;

export type TranscriptionErrorCode =
  (typeof TRANSCRIPTION_ERROR_CODES)[keyof typeof TRANSCRIPTION_ERROR_CODES];

export const TTS_ERROR_CODES = {
  TTS_PROVIDER_UNAVAILABLE: "TTS_PROVIDER_UNAVAILABLE",
  TTS_LATENCY_EXCEEDED: "TTS_LATENCY_EXCEEDED",
  TTS_SWITCH_FAILED: "TTS_SWITCH_FAILED",
  TTS_ALL_PROVIDERS_FAILED: "TTS_ALL_PROVIDERS_FAILED",
  TTS_CONFIG_INVALID: "TTS_CONFIG_INVALID",
  TTS_RECOVERY_PROMOTED: "TTS_RECOVERY_PROMOTED",
} as const;

export type TTSErrorCode =
  (typeof TTS_ERROR_CODES)[keyof typeof TTS_ERROR_CODES];

// Pulse-Maker Component Constants
export const PULSE_SCALE_MIN = 1.0;
export const PULSE_SCALE_MAX = 1.3;
export const PULSE_DURATION_MIN_MS = 500;
export const PULSE_DURATION_MAX_MS = 2000;
export const PULSE_COLOR_DEFAULT = "#3B82F6"; // Electric Blue
export const RIPPLE_DURATION_MS = 300;
export const RIPPLE_SCALE_MAX = 2.0;
export const VOLUME_SPEAKING = 0.8;
export const VOLUME_IDLE = 0.0;
export const VOLUME_DECAY_RATE = 0.95;
export const VOLUME_THRESHOLD = 0.8; // Binary state threshold for MVP
export const RIPPLE_DELAY_1_MS = 50;
export const RIPPLE_DELAY_2_MS = 100;
export const RIPPLE_SIZE_1_PX = 72;
export const RIPPLE_SIZE_2_PX = 60;
export const RIPPLE_SIZE_3_PX = 54;
export const RIPPLE_SPACING_PX = 6;
export const INTERRUPTION_RESET_MS = 500;
export const DECAY_INTERVAL_MS = 100;
